language: python
python:
  - "2.6"
  - "2.7"
#services: mysql
env:
  matrix:
    - DJANGO=1.4.6
    - DJANGO=1.5.4
install:
  - pip install -q Django==$DJANGO --use-mirrors
script:
  - make pep8
  - make pyflakes
  - make test
